### ISSUE TITLE
Disable Nether/Disable Nether Portals

### ISSUE THREAD

**Issue by unpure** [coolsquid/SquidUtils#17]
Hey there.
I'm currently at the starting point of creating a modpack.
The modpack (if everything goes the way it should) will be published on the FTB-Launcher.
I would like to include SquidUtils (and ofc SquidAPI) in this pack.
Because the pack is currently created there are no proper informations about it.
The modpack includes HQM and a small storyline.
At this point 'm asking for permission to use your mods in my modpack.
A link to your post's on MCF/Curse and your Website will be added to the website when done.

Beside of the question about modpack permission i would like to see a way to disable the nether.
Maybe with a config option to completly disable the nether or only the portal building part.
With this option it would still be possible to get into the nether using other ways then the portal.

Sorry for my bad english, i hope its not to hard to understand.

**Comment by coolsquid** [comment]
Permission to redistribute my mods is automatically granted to any pack distributed through the FTB launcher, as long as the following terms are being fullfilled:
- Give credits to "coolsquid".
- Link to http://coolsquid.wix.com/software.
- You are not allowed to earn money from the pack.
- Modpack users should report crashes to the modpack owner. The modpack owner is the only person that should report crashes to me.
- You may not modify the source code of the mod.
- I can revoke the permission at any time.
- I can change the requirements at any time.

I will look into disabling nether portals. I am however not guaranteeing anything.

Have a nice day. :)

**Comment by coolsquid** [comment]
Nether Portal disabling was implemented in b31511987f25b8b48cec66df82906cd535b8ff65. Will be in the next release.
