### ISSUE TITLE
ExtraUtilities:decorativeBlock2 hardness and resistance cannot be changed 

### ISSUE THREAD

**Issue by Kaikaku** [coolsquid/SquidUtils#20]
Neither by config nor by script. Works well with e.g. chisel glass.

**Comment by tattyseal** [comment]
@Kaikaku What version of ExtraUtilities and SquidUtils are you using so we can replicate the issue.

**Comment by coolsquid** [comment]
Should no longer be an issue after the 1.9 rewrite.
