### ISSUE TITLE
Disabled Item left click behavior

### ISSUE THREAD

**Issue by CrazyNagaraj** [coolsquid/SquidUtils#27]
When a item is disabled, if you left click any block with that item in hand, The block breaks and returns to normal in both creative and survival. It should be behave like left clicking with empty hand, Right?.

Try disabling the stone axe(any item) in items.cfg and punch tall grass with disabled item.

EDIT: Not only left clicking on blocks, Left & Right clicking on blocks, entities also do nothing. When you attach a living entity with disabled item, entity hurts, but no damage to entity is done.

I am hoping to see is When a item is disabled it does no special actions performed that item. It would be just crafting item(like minecraft stick) and standard actions performed by any item in hand(like left clicking to break block, right click to open GUI, hurting entities, interact with villagers which are performed by empty hand). So, if i disable the sword, sword behave like a stick in my hand. I think you understand, what i meant to do.

**Comment by coolsquid** [comment]
The current implementation is a bit bad. I'll try to improve it.

**Comment by coolsquid** [comment]
Seems like changing it would require dirty hacking, which I don't really want.
