### ISSUE TITLE
More material config options

### ISSUE THREAD

**Issue by EwyBoy** [coolsquid/SquidUtils#29]
This is the thing I been wanting to talk to you about but never got time to do.

Basically I am looking for a mod that lets me modify how fast I can break the blocks.
This is easy to do for vanilla blocks cause you can just override each individual blocks hardness in the code. But when it comes to modded blocks this is a bit fancier.

So what I though is that if you could loop through all the blocks currently loaded in that specific instance of MC and say if (Material == Stone) then you can set all blocks that is using material stone example to take the current hardness value and multiply it with a optional number from the config file.

So lets say I want to slow down the early game of MC by adding higher hardness value to all blocks in the game. That will make some of the lategame tools much less op and the early game more fun for me as a hardcore player. Then I can go into the config file and say. I want all stone material related blocks to have a additional hardness value of 2.75 example. So lets pretend that smooth stone and cobble has 2 different hardness values. Cobble has 1.5 and stone has 2. Then when it loops through the block in the game it finds cobble. Then I gets the material type of cobble. Since cobble has material stone it now knows it is going to get the cobble stone hardness value and then multiply it by 2.75 since that is specified for all blocks using the material type stone.

Same for all other material types. Use specify a multiplier value in the config for the material type. Then it multiplies that value form the config with all blocks containing that material type.

I though since that thing about that mod is shape your Minecraft experience thing. This is a feature that might fit this mod really well.

If you need some help with the code or to understand what I meant in this feature suggestion just ask.

Stay cool
-Ewy

**Comment by coolsquid** [comment]
I see one major issue; materials do not have names. What would I name each config category?

**Comment by EwyBoy** [comment]
Yeah, I see the problem here. I don't really have any solutions on top of my head either. Cause you can't say like if (MaterialType == Material.Ore) {Then do something;} ??

**Comment by coolsquid** [comment]
Well, I could use the current API, but that would limit the configs to Vanilla materials and materials registered through my API.

**Comment by EwyBoy** [comment]
yeah that is the sad part that is only partially work. The API is fine but the coolest thing would be if I could set up the configs and play modded minecraft with custom hardness to all the blocks mods are adding in.

**Comment by coolsquid** [comment]
I have a [working prototype](https://gist.github.com/coolsquid/2cab714d22a571586095) now.

**Comment by coolsquid** [comment]
Implemented in the newest version. Note that mods have to [use the API](http://coolsquidmc.blogspot.no/2015/05/using-squidutils-api.html) for it to function.
