### ISSUE TITLE
[Feature Request] New gamerule: doWeatherCycle

### ISSUE THREAD

**Issue by SnowShock35** [coolsquid/SquidUtils#31]
Hi @coolsquid 

I wanted to make a feature request for a new gamerule. This gamerule would would act in a similar way to the doDaylightCycle one but instead of effecting time it will effect weather and cause it not to ever activate/deactivate. I think this would be a neat addition as it wont require a clock to be constantly running and telling a command block to do /weather clear 9999.

So that's my idea, let us know what you think.
-Snow ;)

**Comment by coolsquid** [comment]
Doesn't really fit SquidUtils.
