### ISSUE TITLE
Another config option - potion particles

### ISSUE THREAD

**Issue by RedsaphirCZ** [coolsquid/SquidUtils#36]
Hello CoolSquid, is it possible to add config option to disable potion particles?
Thank you.
Keep up the great work!

**Comment by coolsquid** [comment]
Like, disabling *all* types of particles? You can already disable individual ones in the entity config.

**Comment by RedsaphirCZ** [comment]
I'm not sure what "entity config" is. Where can i find it?
Just want to disable all particles made by potions on player, because they are, you know...bad.

**Comment by coolsquid** [comment]
> I'm not sure what "entity config" is. Where can i find it?

Mobs.cfg. Apparently I was wrong though, seems like it doesn't generate for particles. Iiirc, you can disable particles with [sprinkles_for_vanilla](http://minecraft.curseforge.com/mc-mods/226309-sprinkles_for_vanilla).

**Comment by coolsquid** [comment]
Closing. If you have anything to add, just comment and I might reopen the issue.
