### ISSUE TITLE
(Mekanism) I'm unable to change the hardness of Osmium without also changing Copper and Tin

### ISSUE THREAD

**Issue by itanshi** [coolsquid/SquidUtils#39]
http://imgur.com/gallery/ZDsOUzn

I am only able to adjust the hardness/resistance of (Mekanism) osmium, copper, and tin collectively and not individually.

I've gotten this data from cofh ore generation threads, linked below. I understand this is 'metadata' at the end (0,1,2). When I made a :0, it rebuilt the Mekanism:OreBlock entry and now all three have the default hardness/resistance. If I change the default, it ignores 1 and 2.

https://docs.google.com/spreadsheets/d/1TLcyxT9-BPNswQeoHfTcgvYjuuQ7dFu9mzPXijNY8v0/edit#gid=1653685587

Mekanism: 8.1.3.231
Squid Utils: 2.1.2

**Comment by coolsquid** [comment]
I haven't added any configs for metadata, and I'm unsure whether it would be possible. Values like hardness and resistance are stored in the block, not its metadata.

**Comment by itanshi** [comment]
I was afraid it's an issue on Mek's side. i checked their java and by all appearances they are given the same values by one bit of code.

**Comment by itanshi** [comment]
I'll just close this. I found a different way to do it. Thank you for your help.
