### ISSUE TITLE
Using Slash key only opens chat

### ISSUE THREAD

**Issue by Towsty** [coolsquid/SquidUtils#47]
I am not sure what causes this exactly, but it only happens after putting SquidUtils and SquidAPI in a pack. By default, the 'T' key opens minecraft chat and the '/' key opens the chat with the '/' already typed into the chatbox. With SquidUtils and API installed, hitting the '/' key only brings up an empty chat box. 

Any thoughts on this?

**Comment by coolsquid** [comment]
Should be fixed with the 1.9 rewrite.
