### ISSUE TITLE
SquidUtils turns off burning/firespread by default, and there doesn't seem to be a way to turn it back on.

### ISSUE THREAD

**Issue by Twilight13** [coolsquid/SquidUtils#48]
This is with the latest SquidAPI and SquidUtils:
SquidAPI-1.1.15(MC_v1.7.10)
SquidUtils-2.1.4(MC_v1.7.10)

It seems to disable things from burning, or make them non-flammable. If I use flint and steel to set a fire on a floor made of oak planks, the fire will burn on the single spot for a little while, and then go out, without burning the block or spreading, just like if I had set the fire on a block of stone. I've tried lots of times, on planks, logs, etc, and none of them burn, the fire doesn't spread, nothing. The flame appears, but then just goes out after a bit.

I have confirmed that fire works/burns normally with SquidUtils out (Even with SquidAPI still in), and doesn't when I put it back in.

I thought maybe it was some setting in SquidUtils, but wasn't sure which one. I tried deleting the config files, so they'd regenerate, and it still doesn't work with the default, regenerated config settings.

I love SquidUtils, and find it really useful, but this one issue/bug/feature that can't be turned off? is really causing me problems. Let me know if there is anything I can do to help test or narrow things down.

Thanks!

**Comment by Twilight13** [comment]
Just an update:

I used the SquidUtils.cfg under the SquidAPI directory to set various handlers to false and true, trying to figure out which handler was preventing the fire from burning/spreading. I narrowed it down to Blocks.cfg.


When I set the handler to false, like this:

    B:Blocks.cfg=false


Then the fire works. When it is true, it doesn't. I don't know if this helps you troubleshoot things or not, but I just wanted to let you know.

**Comment by Twilight13** [comment]
Another update:
Disabling the Blocks.cfg as mentioned above does allow the fire to work, but then sand and gravel do not fall any more.

**Comment by Twilight13** [comment]
Update:
Got the wood to burn. The problem is in BlockMaterials.cfg

Here's the entry for the vanilla logs:

"minecraft:log" {
    I:flammabilityMultiplier=0
}

If you set the multiplier to 1, it works. I'm assuming that's because if you multiply the flammability by 0 (Which is the default setting, by the way), then no matter what the flammability was, it will now be 0 (Because anything multiplied by 0 is 0). A better default for the flammability multiplier seems like it might be 1.

**Comment by coolsquid** [comment]
The mod has been rewritten for 1.9, and the fundamental design flaw causing this issue has been fixed.
